language: node_js
node_js:
- lts/*
script:
- npx d2-style js check --all
- yarn build
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx @dhis2/cli-utils release --publish npm
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: IqN5jS/r96ChdgkmDs22GC+XB2PpHoYAlJ9P/UxYegFuZaLEStu2z3fo4nlZ1xFRaGTFtPo0KcmJiGPMVPrzqJfA8SBf8vATq1Vlqu/PETbWGKP+J5krXx4O5ccbqU6lJIAdG4sbIOPzVfgWMI9J3mZQaYzy/Ek0qRGA8dWZ3orDZApxMRxgVBn/jbWMh58verX19wb+BbLqDlprSjg84j7imD+XBTaQQm7SpqTT8IWRLzT8s4FPRRGTPqhJS4pyWrz1OJfEnme8BmHC/yo1lMXWe4M1c3iCZXdg3qulfGaJ/Qq2C48QPJMmkvptV0zBvXP7QvX3WUPmPzSJ0SnqykhhCXFIOnpHGEvpvcJY0g64cVeCU6PgcjEN5kekchxny+QAzPRle7n3AQayOP2wEvtvuFOrRIcYT2iWCdLE8t3DNWDT8iLCQVlGonEQa/O2uKnk29YSYxeQb/CtZB8IhsyegNVptdazZhhu6vPBvOcPZoP/KjnPkPKREvpUkJmChpwIcFM6AaPERFWQ4cT9XcXQBJI65Zpd8zzgitRjEcm4vEmoqEqlN/gCx7bHrKZayxnJquAMczA1w4cziF2d01ooFggEaL4Msywn6Kw8LhgoD9td0LsBQJ1en+CVoU44/d008mUF6r5XvMva2PTZxPBeAT7D2c5vhzwgALaxqFE=
  - secure: UoOEm0KpYh5FODo6+/rXfBRJ2R8wS7BiYzda4IAEvQRXyqcz4K09w564A+NIXJ797zFMP2ADpIuSVCkF3RZh46smuw5WhL68FfhICBlPPOHqQE/zVbnV1VvTkQvPN4NXMrYBe8J/gyzhlwTZ6ys2nauZLDa4DR/tCpo5aBxwz09PWZK0N3WvXJCRsfSaGN6zMepJMQPYeX8kDcMhFr9VpIMq3x5bs9YXadHDd6g3XPrusxp+25ItXXyErH9Q0Dly1jUOKW1E+RJg74lQ2UNr/9aTPgk+KFIqW6vVb1l3uRsysKW4BDTc+Ao3+lCnZuiSC6NDD5+aHQrYpkrEtX0/AGNHo35nxAsk2sPTium+tonJUCcE6Q+3o+7ki9dSWDDCCHx4YDSpAB4/4BG1XEyO7ZIbAxWZA763xPsTxpsPaRdvI+IwU6ina2j/p7anGGRWUGbMZMutJ18B10FJO4HO0hno0KWXI2gDM3MXVTWZY2Iwb6Jh/7z87w8WSQP0bSNxa0qYed9wanIIenKrPM19jbVamzAWpEeyVZ7YkDq28bWO+xcyECuExeAr8XHYLWmF5Z4UWUNKaXOVRU9NLaTN8B3NZKPNYvexOeQadDluuchxyJgiCnHndt3TLysl6law2203jVTByPXn7IGt9hP4Pi6wqpxT5lMcrKEHjojCzz8=
