language: node_js
node_js:
- 8.11.1
before_script:
- npm install --global @dhis2/deploy-build
script:
- npm run build
deploy:
    - provider: script
      script: deploy-build
      skip_cleanup: true
      on:
          all_branches: true
    - provider: script
      script: publish-build
      skip_cleanup: true
      on:
          tags: true

env:
  global:
  - secure: WE1+KaIft4r6m2DhX8mzwfFADmTKpYvuwc3I3r6AEti+BMIf7J0TVZ5Biyf+D5Bqnsq/Vh2fb+YAldR4YzPTOe9De/kGXagbW+bLsFthxS3gSVZiZOttmfm/5cwsGfFgtbx7REB9G+tCUvIdbFxQcpx/jmsCFRFd5QwcsfH4oy2eKpxSbQ39WfeLmF/jYzICl43xdlulfsOBU9cq0jqzZqbCNVR50EWQoHLMaec6Z25tSAxJGjJwnEjhI/OWyjepzNJaaNS/m0a9OlI6KCsPgt2Fx8zoeQRKGYZbs81IwoCajbAF4f+Hhvb1c2g/9yw2TNXJAswL4H0UJV4Gzj38hX99kwKwJvmM73QxXUlR+vfK5cFZtZ+PBkIOgXRtmYQRz1KbRHPJNEUaefa7J/xkaJacrzq7ZRHh/tBnApUvpIfOD+qjhbk9NFZYyXwfhfN4/th9H4lIKINUElgMMb5v9FNJtSsI0X3piIXFZXRTXuVGilM/w7ie6tacoCDu8q76EpDMSjW8NJpOh89E2IdVvFQxbZxtwUHgeXcBjMpw6Ewi6qDbDMPE+cajf0aKqnUmRqsCTO3U7u0BgyYn+5MuKj67kiWmjrUGFf8lXYbWru4X1MYcOpqbC6YI/8BBpnDwih7Ag8lEwvdqP8xCe9VuUDU7YsX+fTpDjb5QAtuk8YQ=
  - secure: h/Dy1nYjZIuBNpGql8/hwmDzgh5JFxTHvZkTWOE4zJj2vbJ5d599Z0QcaZdDy4EhnEP8nLP+ASxDiqnc7v3YJ+RAdSWIGx5ey8FeMKrQsckLNnkswVofelsO33yrfmEta78i4xLywWl+1680GVvpSfuGARqbclr/LmM8fvb9ZGc4vG30hrrz6SG3BI4ExVGAv2AeslmSpBiNppg5qouJLk1iJe2pZprp5yRTqBFVa+K2AuWENDCviCyjUhXBoOF8pOt7GW304YfV/H4f0Wekr3kabJ4YqrGDAh12dtz2QV135jIMqXOpxn+gNzPZ5nqOmNCazM96cbIi3SsC5k4968gkHVIvJIkmv8gkS/3XR8C965RWwYhmov7IguHNPieUut1iCvSoO1ZDAhS6ygUTPYpXEv4YOh0HL06NnTIM8A7z2IBxtIfxkUuz4Fl13kcmNRCgQuenJ2eB80tHbSpYajfS3nwDFSaCiTVK5aKlZiT58hM0CjA5qc6cG8W8ckQBz/n75BJ/OO0w9xgAGA+PiuowSPf+INRPJTMi5oob3QqODlQhViboGjPzUlxg/P8M0aTO87RQEdKRZ5m4ikXgC48GjQ9bRlx/2te91qOe0kkhO4x3GEFY3m3rm1rwP2jWwlyEeVZo9VPP97QUE/rdB+3ZyOTRxvElplhnjP96PNI=
