language: node_js
node_js:
- lts/*
script:
- yarn build
deploy:
- provider: script
  skip_cleanup: true
  script:
  - npx @dhis2/cli-utils release --publish npm
  on:
    tags: false
    branch: master
env:
  global:
  - GIT_AUTHOR_NAME=@dhis2-bot
  - GIT_AUTHOR_EMAIL=apps@dhis2.org
  - GIT_COMMITTER_NAME=@dhis2-bot
  - GIT_COMMITTER_EMAIL=apps@dhis2.org
  - secure: B5+Gts6UxzX8rUeIfCYCSoG+Bz0BlPU2dtRr++9amTcSEjTmVWCm6vJHY1/FedMyUM8O+P/gnpKSzq7vJ1mk/EcJQTss6p8T8mce13luY+uqyALtfdT3Ld147MS+2KwodMIxIEIIkUXCBaTbN7EnCatdvQaWgB46fLekoHo6qnJ1GIfThYcqTGGICxKI3GOtg8ooFC5R1dsSzrWDtcKKc4F7x4/FIlVUCwjHHU+j3QvYKNhPVtSs+Mol5rJyaCXpUyPSLf1ZjJQh8IVkp62hfbuhiy8ko/kLcZscZ2xw4FhdbBjCsVhE/0RqpDAnkgLEhkq0L9CUxfV3pAdWR37vsLp/1OhAWbRoHT1xgSpFqZiEIiCDdDwWCsq0/yKSkHaUBkBW8qFfGVLt4Zja0ZDEIUlko0Cxbm/ebFIFQ9BsftBuxrZwTWhfMR5qby1aOYM603rYPoaLhvIRCdrSmBhwZE2wGCXEas/kY00+x1QBShyzRMU+Lzm4Ip++6nw4U5uSkXfpamp7u6TRbdkj1F71Dyw35sjYv3MsATuEoxpSUGp0ewCXbv0dMyAG+aR16H3OJUwEDBlIndUq7OUAuNtvRVdf47VORo2/rQOUtB7BcGJeM8Z59vrVTIOhYz/14Jmyb+6xprLUsyPE4aA/oJuP4ysn0+aMUJfMYjI6PCsN7Vk=
  - secure: dZ9Sz8TopnzTytN0Vsr0kON9S3Ce9d9TD0sCamjTM1SVffBGgMeRGYs+ZrcGOkLIT467nDCfFU1E75SHN97F8+Uu+S+68rUcvqq1jTTRroUdKPcpzuG38V5Y6KRa3zoFU54xozE/OIhKJBrwCzNWjB1Btp2mcA3KN5LwHcrfSExv0DSYXSN6dGNyub2bKs7WQXqVrm4fdpzRV+X0M5Y+rXJKUbRd8xZHsB/JZV6s0w51/TDjMoNTtIIy8LumXKSGmqhPcR8rRZMpMd/YCPUf1m4NJjeHBF7vpBW+Z3tUQCE13dwim/RULVRQ5i51f1wftjr71xE0GG65/xbT3/iWIoTRmmnerkHBIYKyCuZMDSClxRY9CJyZJf5Q6z6HScvZeY2DXigHoyNj1r+h3JVGKB5A2og6CO9ej7mwaAHszYOYnSWpcZ9rBKHXmOYMKh3x36bUtiicGdYOxyRrZ/zOjmiHxZLoMtuL1cxGJb/yLvDQnqMM9PCa50Cn8gqaVEYW8nDhQioY3go1soGDZ9k1H1FqxSww6uxtzE8mYYOi+u9V32LICLkMObHVS7/tEZbWt0lQ3IvyvEn42h1EUy4Yw/GQGUy7yxS2QACTGI8KfmfAXFpdXoYRk4AtOdD/8ColS/pyHmdux2eZTdJBa56jgbkY3ya88SF8run/wyIo35M=
