[build]
  command = "yarn install --frozen-lockfile && yarn build:docs && yarn build:demo"
  publish = "build/docs/"

[[redirects]]
  from = "/*"
  to = "https://ui.dhis2.nu"
  status = 301
  force = true
