version: 1

update_configs:
    - package_manager: 'javascript'
      directory: '/'
      update_schedule: 'daily'
      version_requirement_updates: 'increase_versions'
      target_branch: 'master'
      ignored_updates:
          # ui-core supports 16.8 of react, so ignore all updates
          - match:
                dependency_name: 'react'
                version_requirement: '>=16.9.x'
          - match:
                dependency_name: 'react-dom'
                version_requirement: '>=16.9.x'

      automerged_updates:
          - match:
                dependency_name: '@dhis2/*'
                dependency_type: 'all'
                update_type: 'semver:minor'
          - match:
                dependency_type: 'all'
                update_type: 'security:patch'
