version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_assignees:
      - "@dhis2/front-end"
    ignored_updates:
    # ui-core supports 16.3 of react, so ignore all updates
      - match:
          dependency_name: "react"
          ignored_updates: ">=16.4.x"
      - match:
          dependency_name: "react-dom"
          ignored_updates: ">=16.4.x"
