# For more options:
# https://github.com/cypress-io/github-action

name: 'DHIS2: Cypress'

on: pull_request

jobs:
    cypress-run:
        name: E2E runner
        runs-on: ubuntu-latest
        strategy:
            matrix:
                containers: [1, 2, 3]
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Tests
              uses: cypress-io/github-action@v1
              with:
                  record: true
                  parallel: true
                  start: 'yarn start --quiet --ci'
                  wait-on: 'http://localhost:5000'
                  wait-on-timeout: 120
                  group: 'End-to-End'
              env:
                  STORYBOOK_INCLUDE_TESTING: true
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
