# For more options:
# https://github.com/cypress-io/github-action

name: 'DHIS2'

on: push

jobs:
    cypress-run:
        name: E2E Tests on Firefox
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install Firefox
              run: sudo apt-get install firefox

            - name: Tests
              uses: cypress-io/github-action@v1
              with:
                  browser: firefox
                  record: true
                  parallel: true
                  start: 'yarn start:testing'
                  wait-on: 'http://localhost:5001'
                  wait-on-timeout: 120
                  group: 'e2e-firefox'
              env:
                  CI: true
                  STORYBOOK_TESTING: true
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
