name: 'DHIS2: Lint'

on: [push]

jobs:
    pr:
        name: Code style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x

            - name: Lint
              run: |
                  yarn install
                  yarn lint
